global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hotel-booking-system'

scrape_configs:
  # Hotel Service (Gateway)
  - job_name: 'hotel-service'
    static_configs:
      - targets: ['hotel:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Audit Service
  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Discount Analytics Service
  - job_name: 'discount-analytics-service'
    static_configs:
      - targets: ['discount-service:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Booking Orchestrator Service
  - job_name: 'booking-orchestrator-service'
    static_configs:
      - targets: ['booking-orchestrator:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zipkin'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'zipkin:9411' ]
